name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:lts

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run type check
        run: yarn run type-check
      - name: Run linter
        run: yarn run lint
      - name: Run tests
        run: yarn test
